name: "create release candidate"
on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: "actions/checkout@v3"

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: develop

      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ steps.semver.outputs.next }}
          fromTag: ${{ steps.semver.outputs.next }}

      - name: "Create release branch"
        run: |
          echo '${{ steps.changelog.outputs.changes }}'
          git checkout -b release/${{ steps.semver.outputs.next }} && git push origin release/${{ steps.semver.outputs.next }}
          gh pr create --base production --title 'Update prod to latest release' --body 'Needs to execute Jenkins after prod update'
        env:
          GH_TOKEN: ${{ github.token }}

      - name: "Produce summary"
        run: echo '${{ steps.changelog.outputs.changelog }}' >> $GITHUB_STEP_SUMMARY
