name: "create release candidate"
on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: "actions/checkout@v3"

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: develop

      - name: "Create release branch"
        run: |
          echo '${{ steps.semver.outputs.current }}'
          echo '${{ steps.semver.outputs.next }}'
          git checkout -b ${{ steps.semver.outputs.next }} && git push origin release/${{ steps.semver.outputs.next }}
          gh pr create --base production --title 'Update prod to latest release' --body 'Needs to execute Jenkins after prod update'
