name: "create release candidate"
on:
  workflow_dispatch:

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: "actions/checkout@v3"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-branch: develop
          skip-commit: true
          skip-version: true
          skip-tag: true
          create-summary: true

      - name: "Create release branch"
        run: |
          git checkout develop
          git checkout -b release/${{ steps.changelog.outputs.tag }} && git push origin release/${{ steps.changelog.outputs.tag }}
          gh pr create --base main --title 'Update main to latest release' --body 'Needs to execute Jenkins after prod update'
        env:
          GH_TOKEN: ${{ github.token }}

