name: "on update production branch"
on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout..."
        uses: "actions/checkout@v3"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-branch: origin/production
          create-summary: true
          skip-commit: true
          skip-version: true
          skip-tag: false

      - name: "Create backmerge PR"
        run: "gh pr create --base develop --head production --title 'Backmerge prod into develop' --body 'This PR was automatically created by the backmerge workflow.'"
        env:
          GH_TOKEN: ${{ github.token }}

